---
gitlab_initial_root_password: 'Net0logy@'
gitlab_initial_shared_runners_registration_token: 'My@wes0meT0k#n'
gitlab_runner_registration_token: "{{ gitlab_initial_shared_runners_registration_token }}"
