---
node_exporter_open_port: yes

wp_db_name: wordpress
wp_db_user: wordpress
wp_db_password: wordpress

wp_uri: "https://www.{{ domain_name }}"
wp_site_title: "Netology" 
wp_site_admin_name: "superadmin" 
wp_site_admin_password: "SuperP@ssw0rd" 
wp_site_admin_email: superadmin@example.com
